# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
        ('pong_rank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PongGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('percent', models.FloatField()),
                ('loser1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pong_loser1', to='house.Player')),
                ('loser2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pong_loser2', to='house.Player')),
                ('winner1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pong_winner1', to='house.Player')),
                ('winner2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pong_winner2', to='house.Player')),
            ],
        ),
        migrations.RenameField(
            model_name='pongscore',
            old_name='pong_losses',
            new_name='games_played',
        ),
        migrations.RenameField(
            model_name='pongscore',
            old_name='pong_wins',
            new_name='losses',
        ),
        migrations.RenameField(
            model_name='pongscore',
            old_name='pong_mu',
            new_name='mu',
        ),
        migrations.RenameField(
            model_name='pongscore',
            old_name='pong_score',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='pongscore',
            old_name='pong_sigma',
            new_name='sigma',
        ),
        migrations.AddField(
            model_name='pongscore',
            name='win_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pongscore',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
