# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('percent', models.FloatField()),
                ('loser1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loser1', to='house.Player')),
                ('loser2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='loser2', to='house.Player')),
                ('winner1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner1', to='house.Player')),
                ('winner2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner2', to='house.Player')),
            ],
        ),
        migrations.CreateModel(
            name='PoolScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('win_percent', models.FloatField(default=0)),
                ('mu', models.FloatField(default=25.0)),
                ('sigma', models.FloatField(default=8.333333333333334)),
                ('score', models.FloatField(default=0.0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='house.Player')),
            ],
        ),
    ]
