# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pool_rank', '0002_auto_20170601_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolgame',
            name='loser1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_loser1', to='house.Player'),
        ),
        migrations.AlterField(
            model_name='poolgame',
            name='loser2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pool_loser2', to='house.Player'),
        ),
        migrations.AlterField(
            model_name='poolgame',
            name='winner1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_winner1', to='house.Player'),
        ),
        migrations.AlterField(
            model_name='poolgame',
            name='winner2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pool_winner2', to='house.Player'),
        ),
    ]
