# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('netid', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
