# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PongScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pong_wins', models.IntegerField(default=0)),
                ('pong_losses', models.IntegerField(default=0)),
                ('pong_mu', models.FloatField(default=25.0)),
                ('pong_sigma', models.FloatField(default=8.333333333333334)),
                ('pong_score', models.FloatField(default=0.0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='house.Player')),
            ],
        ),
    ]
